blank_issues_enabled: true
contact_links:
  - name: DevOps Incident Analyzer Discussions
    url: https://github.com/jadhav-prathamesh/New-Projects/discussions
    about: Please ask and answer questions here.

